### ISSUE TITLE
url mark up is malformed

### ISSUE THREAD

**Issue by Schmell** [edit4ever/script.module.zap2xml#1]
I read your posts on FastEddieCurrents repo
on line 1423 
replace
`fh.write("\t\t<url>" + programs[p]["url"] + "\" />\n")`
with
`fh.write("\t\t<url>" + programs[p]["url"] + "\"< /url>\n")`
to correct malformed xml
I am using openelec as well. Good work on this.

**Comment by edit4ever** [comment]
Thanks for that - I've committed the change but will not be near a test system for a few days.  Hopefully others can check out the fix.
