### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Schmell** [edit4ever/script.module.zap2xml#11]
I have had some problems with the sorting. mainly having multiple bullets with empty strings.
I have an idea on how to rework your script that should fix this issue and reduce the amount of code used.
My question is do you want the ability to use different separators or will just one choice work? 
One choice could make the kodi settings easier to manage.

**Comment by edit4ever** [comment]
I was trying to give as much flexibility as possible.  Some people will want separators - some won't.  Some people like bullets, some people like commas - some want it between some of the items some want it between all of the items.  I had added the code to remove multiple occurences of bullets and hyphens (albeit it's a bit messy).  We're you still seeing the duplicates with the current version?

I'm open to suggestions - but the goal is flexibility.  I'm actually considering breaking it out into a separate screen, similar to the way you build custom menus in a skin.  Then just pull that config back into the instructions.  Also, right now I'm passing it to the zap2xml.py as an arguement - but I think we could rework it to have the zap2xml.py look to the setting file itself.

One of the biggest issue right now is the way I wrote it breaks the encoding - so Spanish language (and other characters) are getting messed up on the output.  I'm still learning python - so feel free to suggest streamlines!

**Comment by Schmell** [comment]
The problem is simple, but becomes hard to fix when defining explicit separators. If there was no content it will move to next and insert a separator, which your code fixes unless there is multiple blanks.
I understand where you are coming from though and i will keep working to provide maximum flexibility for formatting the output.
As for the Spanish content i don't get any from my schedules so it will be hard for me to troubleshoot that problem. I am very new to python as well, but have some experience with interpretive languages, so i will do what i can to help.

**Comment by edit4ever** [comment]
BTW - you could always setup a test account (with a different email) on zap2it with a simple broadcast lineup from a border city - like San Diego - and then just set a couple of stations as your favorites.  This will keep your test downloads quick and allow you to test Spanish language descriptions.  :-)

**Comment by Schmell** [comment]
Ya. Good idea. Is that where you are from?

**Comment by edit4ever** [comment]
Well - I wouldn't say I'm _from_ there - but that's where I live now!
