### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by Schmell** [edit4ever/script.module.zap2xml#12]
How are you testing? i Think it would be good to put in a test option that only read from the cache regardless of its age. Its a pain because when you run option -D it takes anywhere from 20 - 60min to get the data

**Comment by edit4ever** [comment]
I run a normal test to make sure it doesn't break the login. But I set it to 1 day ( -d 1 ) in order to keep the download fast. 

FYI - Sent you an email for direct questions.
