### ISSUE TITLE
Type error logging into TVGuide

### ISSUE THREAD

**Issue by sjconstantin** [edit4ever/script.module.zap2xml#25]
[zap2xml.log](https://github.com/edit4ever/script.module.zap2xml/files/1608983/zap2xml.log)
I have encountered an error while trying to use TVGuide as a source with v0.7.5.  Log file attached.

**Comment by edit4ever** [comment]
Can you try this version...
[script.module.zap2xml-0.7.6-TEST.zip](https://github.com/edit4ever/script.module.zap2xml/files/1608991/script.module.zap2xml-0.7.6-TEST.zip)

**Comment by sjconstantin** [comment]
After installing that version zap2xml no longer shows up in tvheadend as a grabber.

**Comment by edit4ever** [comment]
Please use zap2epg going forward.
