### ISSUE TITLE
Zap2It 404 Error

### ISSUE THREAD

**Issue by sjconstantin** [edit4ever/script.module.zap2xml#26]
Using Zap2It as a source returns a 404 error.
[zap2xml.log](https://github.com/edit4ever/script.module.zap2xml/files/1609002/zap2xml.log)

**Comment by edit4ever** [comment]
I haven't looked at the TVGuide stuff in a long time as I just used the code from the previous work done by another author.  I can possibly take a look and see if tvguide has changed their site - but if you're looking for an updated, reliable xmltv grabber and are using kodi/tvheadend... take a look at my zap2epg repo.

**Comment by edit4ever** [comment]
I was just able to generate an xmltv.xml file from tvguide using my login.  If you're using a the command line version to run the program, have you entered your username and password and zipcode into the line?

zap2xml.py -z -u USERNAME -p PASSWORD -d DAYS -Z ZIPCODE

**Comment by sjconstantin** [comment]
I ran from the command line and received an error albeit a different one.  Just FYI the log in this issue is for zap2it, looks they have changed/disabled their API.
[zap2xml.log](https://github.com/edit4ever/script.module.zap2xml/files/1609067/zap2xml.log)
This is with your 0.7.6 test version.

**Comment by sjconstantin** [comment]
I'll look at your zap2epg repo.  Thanks for the help.

**Comment by sjconstantin** [comment]
It looks like zap2epg will do the trick!  Thanks for the help and maintaining these repos.

**Comment by edit4ever** [comment]
Thanks for the feedback.  I built zap2epg in preparation of zap2it site changes.
