### ISSUE TITLE
-master

### ISSUE THREAD

**Issue by Schmell** [edit4ever/script.module.zap2xml#3]
when downloading from github repo the folder is extracted as "script.module.zap2xml-master" and this breaks the bash in tv_grab_zap2xml. Is there a way to have the folder in the zip not have the -master added to the name?

**Comment by edit4ever** [comment]
I'm not near my test system - but I just updated the bash line...can you test and see if that fixes the executable issue?  I've created a release version to see if that helps the issue as well.

**Comment by edit4ever** [comment]
Now using release versions.
